services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: portfolio-website-prod
    container_name: portfolio-website-prod-cont
    ports:
      - "4400:80"
    restart: always
    cpu_period: 100000      # Default is 100,000 microseconds (100ms)
    cpu_quota: 5000        # 5% of the total CPU time