name: Portfolio App Testing
run-name: ${{ gitea.actor }} is testing Portfolio App
on: [push]

jobs:
  Portfolio Runner:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: docker compose version
      - name: Check out repository code
        uses: actions/checkout@v4
        # Run tests
